services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bp
      - local
  next-server:
    image: next-server
    container_name: bp-next
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - bp

volumes:
  postgres_data:

networks:
  local:
    driver: host
  bp:
    driver: bridge