services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  next-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

volumes:
  postgres_data:
