services:
  database:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bp
  next-server:
    image: next-server
    container_name: next-server
    depends_on:
      - database
    volumes:
      - .env:/app/.env
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - bp
      - Strapi

volumes:
  postgres_data:

networks:
  bp:
    driver: bridge
  Strapi:
    external: true
